### ISSUE TITLE
How is this different from protobuf etc.?

### ISSUE THREAD

**Issue by dkrikun** [tnajdek/schema-messages-python#1]

**Comment by tnajdek** [comment]
You're right it's similar, here are couple of few major differences from Protobuf:
- Schema Messages is much simpler (and more limited!) which results in some performance increase
- Schema Messages has built-in, transparent support for more than one message within a bytestream/buffer. With Protobuf you need to implement this yourself (usually by storing the length of the message ahead of the message itself)
- Schema Messages has built-in, transparent mechanism for recognizing messages coming on the network stream. With Protobuf you need to know exactly what message is represented in the bytestream/buffer.

Schema Messages is a simpler, lighter version that I've found more suitable for developing browser-based, multiplayer games.

Please feel free to re-open the issue if you have more questions!

**Comment by dkrikun** [comment]
Thanks!

Regarding recognizing messages, isn't it the case that both have to have
the schema to parse the message?

**Comment by tnajdek** [comment]
That's correct @dkrikun, both Protobuf and Schema Messages require pre-shared schema in order to work correctly. The difference is how you deal with messages in your application. Let's say you have two types of message: Foo and Bar. Let's say you get data from from network, you need to explicitly know ahead of time whether it's Foo or Bar message, deserialisation would look like this for Foo:

```
msg = messages_pb2.FooMessage.FromString(data)
```

and like this for Bar:

```
msg = messages_pb2.BarMessage.FromString(data)
```

If you're extracting message using wrong schema it will most likely throw an exception so you can try another one, but that's not very elegant is it? Of course you could implement your own way of identifying protobuf messages!

With Schema Messages it's taken care of! Somewhere in your init you do:

```
FooMessage = factory.get('FooMessage')
BarMessage = factory.get('BarMessage')
```

and then in your code:

```
msg = unpack_message(data, factory)
if(msg == FooMessage):
    print("It's Foo")
else:
    print("It's Bar")
```
